$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: feature_replace_missing_values
display_name: Replace Missing Values
version: 1
type: command
inputs:
  input_data:
    type: uri_folder
outputs:
  output_data:
    type: uri_folder
code: ../scripts
environment: azureml://registries/azureml/environments/lightgbm-3.3/versions/2
command: >-
  python feature_replace_missing_values.py 
  --input_data ${{inputs.input_data}}
  --output_data ${{outputs.output_data}}
